CREATE DATABASE SIGED;
GO
USE SIGED;
GO

CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ROL VARCHAR(50) NOT NULL
);
GO

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    ID_ROL INT NOT NULL, -- FK DE LA TABLA ROL
    NOMBRE_USUARIO VARCHAR(50) NOT NULL, 
    CONTRASENA VARCHAR(255) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT 1
);
GO
ALTER TABLE USUARIOS
    ADD CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);
GO

CREATE TABLE DOCENTE (
    ID_DOCENTE INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT NOT NULL, -- FK DE LA TABLA USUARIOS
    NOMBRE_DOCENTE VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO_DOCENTE VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO_DOCENTE VARCHAR(100) NOT NULL,
    RFC VARCHAR(13) NOT NULL UNIQUE,
    CURP VARCHAR(18) NOT NULL UNIQUE,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO_DOCENTE VARCHAR(15),
    ACTIVO BIT NOT NULL DEFAULT 1 -- 1 = ACTIVO, 0 = INACTIVO
);
GO
ALTER TABLE DOCENTE
    ADD CONSTRAINT FK_DOCENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
GO

CREATE TABLE ESTATUS_EXPEDIENTE (
    ID_ESTATUS_EXP INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ESTATUS VARCHAR(50) NOT NULL
);
GO

CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_CONVOCATORIA VARCHAR(100) NOT NULL,
    ANIO INT NOT NULL,
    DESCRIPCION NVARCHAR(MAX),
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT 1 -- 1 = ACTIVO, 0 = INACTIVO
);
GO

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT PRIMARY KEY IDENTITY(1,1),
    ID_DOCENTE INT NOT NULL, -- FK DE LA TABLA DOCENTE
    ID_CONVOCATORIA INT NOT NULL, -- FK DE LA TABLA CONVOCATORIA
    ID_ESTATUS_EXP INT NOT NULL, -- FK DE LA TABLA ESTATUS_EXPEDIENTE
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_CIERRE DATETIME NULL, 
    ACTIVO BIT NOT NULL DEFAULT 1 -- 1 = ACTIVO, 0 = INACTIVO
);
GO
ALTER TABLE EXPEDIENTE
    ADD CONSTRAINT FK_EXPEDIENTE_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE);
ALTER TABLE EXPEDIENTE
    ADD CONSTRAINT FK_EXPEDIENTE_CONVOCATORIA FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA(ID_CONVOCATORIA);
ALTER TABLE EXPEDIENTE
    ADD CONSTRAINT FK_EXPEDIENTE_ESTATUS FOREIGN KEY (ID_ESTATUS_EXP) REFERENCES ESTATUS_EXPEDIENTE(ID_ESTATUS_EXP);
GO


CREATE TABLE ESTATUS_DOCUMENTO (
    ID_ESTATUS_DOCUMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ESTATUS VARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_DEPARTAMENTO VARCHAR(100) NOT NULL,
    SIGLAS NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE TIPO_DOCUMENTO (
    ID_TIPO_DOCUMENTO INT PRIMARY KEY IDENTITY(1,1),
    CLAVE VARCHAR(50) NOT NULL,
    NOMBRE_TIPO VARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255) NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL -- FK DE LA TABLA DEPARTAMENTO
);
GO
ALTER TABLE TIPO_DOCUMENTO
    ADD CONSTRAINT FK_TIPO_DOCUMENTO_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);
GO

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_EXPEDIENTE INT NOT NULL, -- FK DE LA TABLA EXPEDIENTE
    ID_TIPO_DOCUMENTO INT NOT NULL, -- FK DE LA TABLA TIPO_DOCUMENTO
    ID_ESTATUS_DOCUMENTO INT NOT NULL, -- FK DE LA TABLA ESTATUS_DOCUMENTO
    ID_USUARIO_CREADOR INT NOT NULL, -- FK DE LA TABLA USUARIOS
    NOMBRE_ARCHIVO_ORIGINAL VARCHAR(100) NOT NULL,
    FOLIO_INTERNO VARCHAR(50) NOT NULL,
    FECHA_CARGA DATETIME NOT NULL DEFAULT GETDATE(),
    OBSERVACIONES NVARCHAR(MAX),
    NOMBRE_DOCUMENTO VARCHAR(100) NOT NULL,
    RUTA_ARCHIVO VARCHAR(255) NOT NULL,
    FECHA_SUBIDA DATETIME NOT NULL DEFAULT GETDATE(),
    ACTIVO BIT NOT NULL DEFAULT 1 -- 1 = ACTIVO, 0 = INACTIVO
);
GO
ALTER TABLE DOCUMENTO
    ADD CONSTRAINT FK_DOCUMENTO_EXPEDIENTE FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE);
ALTER TABLE DOCUMENTO
    ADD CONSTRAINT FK_DOCUMENTO_TIPO_DOCUMENTO FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO);
ALTER TABLE DOCUMENTO
    ADD CONSTRAINT FK_DOCUMENTO_ESTATUS_DOCUMENTO FOREIGN KEY (ID_ESTATUS_DOCUMENTO) REFERENCES ESTATUS_DOCUMENTO(ID_ESTATUS_DOCUMENTO);
ALTER TABLE DOCUMENTO
    ADD CONSTRAINT FK_DOCUMENTO_USUARIO_CREADOR FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIOS(ID_USUARIO);
GO

CREATE TABLE VALIDACION_DOCUMENTO (
    ID_VALIDACION_DOCUMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_DOCUMENTO INT NOT NULL, -- FK DE LA TABLA DOCUMENTO
    ID_USUARIO_VALIDADOR INT NOT NULL, -- FK DE LA TABLA USUARIOS
    FECHA_VALIDACION DATETIME NOT NULL DEFAULT GETDATE(),
    OBSERVACIONES NVARCHAR(MAX),
    RESULTADO BIT NOT NULL -- 1 = VALIDO, 0 = NO VALIDO
);
GO
ALTER TABLE VALIDACION_DOCUMENTO
    ADD CONSTRAINT FK_VALIDACION_DOCUMENTO_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO);
ALTER TABLE VALIDACION_DOCUMENTO
    ADD CONSTRAINT FK_VALIDACION_DOCUMENTO_USUARIO FOREIGN KEY (ID_USUARIO_VALIDADOR) REFERENCES USUARIOS(ID_USUARIO);
GO

CREATE TABLE HISTORIAL_EXPEDIENTE (
    ID_HISTORIAL INT PRIMARY KEY IDENTITY(1,1),
    ID_EXPEDIENTE INT NOT NULL, -- FK DE LA TABLA EXPEDIENTE
    ID_ESTATUS_EXP INT NOT NULL, -- FK DE LA TABLA ESTATUS_EXPEDIENTE
    ID_USUARIO INT NOT NULL, -- FK DE LA TABLA USUARIOS
    FECHA_CAMBIO DATETIME NOT NULL DEFAULT GETDATE(),
    COMENTARIO NVARCHAR(MAX) NOT NULL
);
GO
ALTER TABLE HISTORIAL_EXPEDIENTE
    ADD CONSTRAINT FK_HISTORIAL_EXPEDIENTE_EXPEDIENTE FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE);
ALTER TABLE HISTORIAL_EXPEDIENTE
    ADD CONSTRAINT FK_HISTORIAL_EXPEDIENTE_ESTATUS FOREIGN KEY (ID_ESTATUS_EXP) REFERENCES ESTATUS_EXPEDIENTE(ID_ESTATUS_EXP);
ALTER TABLE HISTORIAL_EXPEDIENTE
    ADD CONSTRAINT FK_HISTORIAL_EXPEDIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
GO

SELECT * FROM EXPEDIENTE;